### ISSUE TITLE
can not  reproduce the result in your paper

### ISSUE THREAD

**Issue by alphadl** [syxu828/Graph2Seq-0.1#1]
My setting and data is totally implemented from your repository, I see from your paper that the results of "Path Finding" is 99.99 %, however, after running 100 epochs（which  is your default epoch number）, the best acc on Dev is only 0.145, and  the best acc on Test is only 0.119 which is extremely different from what you have got .

I want to reproduce your results as the paper said. Is there any tricks I missed or something else?

Thanks for your patience~

**Comment by syxu828** [comment]
See https://github.com/IBM/Graph2Seq for details :-)
